name: Daily Python Script Run

on:
  schedule:
    - cron: '0 6 * * *'  # Runs daily at 6:00 AM UTC, equivalent to midnight Central Time
  workflow_dispatch:  # Allows manual triggering

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Replace '3.x' with the required Python version

      # Step 3: Install dependencies (if required)
      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Step 4: Run your Python script
      - name: Run the Python script
        run: python daily_script.py

      # Step 5: Configure Git for commit
      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      # Step 6: Commit changes
      - name: Commit changes
        run: |
          git add -A
          git commit -m "Daily update from scheduled workflow" || echo "No changes to commit"

      # Step 7: Push changes back to the repository
      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push
